lib/reporter.js, test/reporter.spec.coffee
=> fix: skip directory creation when reporting to console

README.md, lib/preprocessor.js, package.json, test/preprocessor.spec.coffee
Allow any Istanbul instrumenter to be used in the karma-coverage.
Will help #120
Closes #101 #49
BREAKING CHANGE: Karma-coverage does not ship with additional instrumenter. You need to explicitly install the instrumenter you need.
Removed **Ibrik** instrumenter that need to be installed explicitly.
Quick list of known community instrumenters :
- [Ibrik](https://github.com/Constellation/ibrik) (CoffeeScript files instrumenter).
- [Ismailia](https://github.com/Spote/ismailia) (ES6 files instrumenter using Traceur).
- [Isparta](https://github.com/douglasduteil/isparta) (ES6 files instrumenter using 6to5).
=> feat(preprocessor): free instrumenter

README.md
It seems that older versions of Karma (0.10.x at least) would output
`coverage-final.json` by default. Newer versions no longer do this and
require the reporter type to be specified.
See for instance the issue in [`grunt-istanbul-coverage`](https://github.com/daniellmb/grunt-istanbul-coverage/issues/14) that was caused by this.
=> Adds `json` reporter type to README.

README.md, lib/coverageMap.js, lib/preprocessor.js, lib/reporter.js, test/coverageMap.spec.coffee, test/preprocessor.spec.coffee, test/reporter.spec.coffee
I would love the ability to include all sources in my coverage reports, otherwise it gives me a false sense of confidence about my coverage. In my testing, this does the trick by adding stubs for all instrumented files to the Collector.
Happy to take any feedback to make this better.
Should resolve https://github.com/karma-runner/karma-coverage/issues/125
=> feat: add support for including all sources in coverage data

lib/reporter.js, test/reporter.spec.coffee
Simple check when using browserify for coverage and there is nothing in sourceCache.
Example of [karma.conf.js](https://github.com/piecyk/image-shop/blob/IS-4/test/karma.conf.js) with browserify and karma-coverage.
=> fix: when using browserify dont create source code caching

README.md
The URL is not the original Istanbul repository. I fixed the link.
=> docs(readme): correct link to istanbul

lib/reporter.js, test/reporter.spec.coffee
- Merges the coverageReporter config with the options passed to each reporter.
- Merges in specified watermarks with the Istanbul defaults so that only some types need to be specified.
Closes #143, #144
=> fix: watermarks are not handled correctly

README.md, lib/reporter.js
change `coverageReporter` options to allow for specifying `sourceStore`, this
is an instance of `istanbul.Store` to look up source files. This allows using
external coverage collectors like `browserify-istanbul` for instrumenting code.
references #16, #123, #124
=> fix: reporter allow using a externally provided source cachere for reporters

lib/preprocessor.js, package.json
Pending https://github.com/gotwarlost/istanbul/pull/349, which is needed to fix istanbul sourcemap outputs to have the correct offset.
Adds sourcemap support to the preprocessor. If the file being
processed has a sourcemap property, it is merged with the output
from the coverage instrumentation. This enables better debugging
on instrumented code.
Closes #109
=> feat(preprocessor): Add sourcemap support

LICENSE-istanbul, README.md, lib/reporter.js, test/reporter.spec.coffee
Add check option to coverageReporter options. Supports similar
options to istanbul's check-coverage feature.
It will cause karma to return a non-zero exit code if coverage
thresholds are not met.
Closes #21
=> feat(reporter): add check coverage thresholds

lib/preprocessor.js, test/preprocessor.spec.coffee
According to the [spec](https://github.com/gotwarlost/istanbul/blob/master/coverage.json.md), the absolute file path should be used in the coverage report. Currently karma-coverage substitutes this with a path relative to `baseDir`. This causes problems when trying to combine coverage with other reports not generated by karma-coverage.
Fixing this would help with #1.
=> fix(preprocessor): use absolute paths

lib/preprocessor.js
This ensures paths are using backslashes in windows, consistent with outputs from istanbul.
=> Paths in windows use backslash (fixes #178)

lib/preprocessor.js
When using the `includeAllSources` flag, every other non-tested file is included.  This appears to be because the `coverageObjRegex` is global and shared.  Resetting the regex allows files to match correctly when `coverageObjRegex.exec()` is called.
Likely to help partially resolve https://github.com/karma-runner/karma-coverage/issues/166, if not completely.
=> fix(preprocessor) Reset coverageObjRegex before each use

README.md, docs/configuration.md, examples/coffee-requirejs/calculator.coffee, examples/coffee-requirejs/karma.conf.coffee, examples/coffee-requirejs/package.json, examples/coffee-requirejs/requirejs.karma.coffee, examples/coffee-requirejs/test.coffee, gruntfile.js, lib/preprocessor.js, package.json, test/preprocessor.spec.coffee
Adds support for using RequireJS with CoffeeScript code by changing
the file extension from `.coffee` to `.js`. RequireJS automatically
adds the `.js` suffix to files and it doesn't seem possible to change
it.
Closes #177 
An example project is included in the `examples/coffee-requirejs` folder.
=> fix(preprocessor): Support CoffeeScript when using  RequireJS

docs/configuration.md
...browser name *accross* different
...browser name *across* different
=> docs: Fix typo in configuration

lib/in-memory-report.js, lib/index.js, lib/reporter.js, test/in-memory-report.spec.coffee, test/index.spec.coffee, test/reporter.spec.coffee
Added the 'in-memory' reporter which raises an event rather than writing the report to disk. I register the report to Istanbul so it uses its factory method design pattern to create the reporter.
resolve issue #215
=> feat(in-memory-reporter) Added "in-memory"  reporter

lib/preprocessor.js
This fixes an issue related to Karma dying when is watching files via `singleRun: false`. Please read issue at https://github.com/karma-runner/karma/issues/1783
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/karma-runner/karma-coverage/204)
=> fix(preprocessor): Call done with error message instead of populating instrumentedCode

lib/reporter.js
Hello, I've been [working on providing a more sustainable coverage solution for a project called "jspm-karma"](https://github.com/Workiva/karma-jspm/pull/147), and if okay with you guys, I would like to use the reporter files for karma-coverage as is. All I really need are callbacks into the `writeReport` and `onExit` functions. Let me know if this is doable, thanks in advance.
=> Adding event callbacks for "writeReport" and "onExit" functions

docs/configuration.md
Add `none` as possible value for reporter type.
Istanbul supports a report implementation that does nothing, called `none`. This report can be used when no reporting is needed.
=> docs(config): Add none as possible value for type

package-lock.json, package.json
This avoid the deprecation warning being printed on `npm install` for packages with a dependency on karma-coverage.
All the uses of istanbul have been replaced with the new istanbul API packages, so this dependency is currently unused.
=> Remove unused istanbul dependency

.travis.yml
- move xvfb to services
- Remove update npm (it was need for old versions of node)
=> Make travis file simpler

lib/preprocessor.js, package.json, test/preprocessor.spec.coffee
Instead of combining source maps manually, this is handled automatically by `istanbul-lib-instrument` when passing the input source map in as an argument in the `instrument` call.
With the removal of combining source maps, the source-map package is not longer needed.
The preprocessor test mocks have been updated to include the necessary mocked functions. The updated mocks don't change what is being tested.
--- 
I've created a playground to test karma-coverage [here](https://github.com/pr1sm/karma-coverage-playground/). The [master ](https://github.com/pr1sm/karma-coverage-playground/tree/346f42bfd71fef3b7f1cc84d1ff26d58ec247ed8) branch (at the time of creating this PR) is using my patch and the generated reports are correct for the few languages I tested (available …
=> Update Source Map Handling

lib/reporter.js, test/reporter.spec.js
onComplete are async method which should bw complete in onExit method
=> fix(report): waiting promise resolve in onExist method fix #418

lib/reporter.js, test/reporter.spec.js
The creation of parent directories is asynchronous process, which was not properly awaited, which resulted in the coverage reports not being written to the disk sometimes as Karma process has exited before the reporter completed the writing of the coverage report.
Also update the test case to use async implementation of the corresponding stub to prevent regressions in the future. ~~It seems that manually calling `done` parameter in several tests was an attempt to solve the same race condition in the unit tests. They are not needed anymore.~~ Nah, probably they are just leftovers of the old reporter implementation.
Fixes #434
=> fix: race condition between the Karma shutdown and coverage writing

package-lock.json, package.json
This allows users of Karma to use modern features such as top-level
await, which is pulled in by the newest versions of Istanbul.
=> fix: update Istanbul packages
